# Generated by Django 5.2.13 on 2026-04-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('acao', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('detalhe', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'log de e-mail',
                'verbose_name_plural': 'logs de e-mails',
                'ordering': ['-criado_em'],
            },
        ),
    ]
