# Generated by Django 5.2.13 on 2026-04-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_emaillog_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
